import sys 
if sys.argv[1]=="mae":
    import mae.eval
elif sys.argv[1]=="rmse":
    import rmse.eval
elif sys.argv[1]=="train":
    import train.train
elif sys.argv[1]=="jax_md":
    import JAX_MD.md
elif sys.argv[1]=="jax_md_as":
    import JAX_MD_AS.md
